#!/usr/bin/env bash

PATH="../../bin:$PATH"

trap 'rm -f tmpfile' EXIT

echo 'echo foo; echo bar >&2' | shall -l sh -q >tmpfile || exit
fgrep -q 'foo' tmpfile && exit 1
fgrep -q 'bar' tmpfile || exit
exit 0